nodes = {
  signal = {
        type = "signal.v2"
        rate = 10.0
        realtime = true
        limit = 100

        in = {
            signals = ({ name = "pulse1",  signal = "pulse",  frequency = 1.0, pulse_width = 1, pulse_high = 1, pulse_low = 0 })
            }
    },

    file = {
        type = "file"
        format = "csv"
        uri = "/results/results.txt"
    }

}

paths = (
    {
        in = "signal"
        out = "file"
        hooks = ( 
          {
            type = "lua"
            use_names = true
            script = "/script.lua"
          },
          { type = "print" } 
        )

    }
)
