services:
  fmu:
    build:
      context: .
  villas-node:
    build:
      context: node/
      dockerfile: ./packaging/docker/Dockerfile.debian
    volumes:
      - ./gateway.conf:/config.conf
      - ./results:/results
    command: ["node", "/config.conf"]
    ports:
      - "8080:8080"
