services:
  grpc-fmu:
    build:
      context: .
    ports:
      - "50051:50051"
  villas-node:
    image: fmu_villas
#    build:
#      dockerfile: node/packaging/docker/Dockerfile.debian
    volumes:
      - ./gateway.conf:/config.conf
      - ./results:/results
    command: ["node", "/config.conf"]
    ports:
      - "8080:8080"
