# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

http = {
    port = 8080
}

nodes = {
    fmu = {
        type = "gateway"

        format = "protobuf"

        gateway_type = "gRPC"
        address = "localhost:50051"
    },

    file = {
        type = "file"
        format = "csv"
        uri = "/results/results.txt"
    }

}

paths = (
    {
        in = "fmu"
        out = "file"
        hooks = ( { type = "print" } )
    }
)
