// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FMU.proto
// Protobuf C++ Version: 6.31.0

#include "FMU.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace FMU_server {

inline constexpr Reference::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ref_{},
        _ref_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Reference::Reference(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Reference_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReferenceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReferenceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReferenceDefaultTypeInternal() {}
  union {
    Reference _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReferenceDefaultTypeInternal _Reference_default_instance_;
}  // namespace FMU_server
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_FMU_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_FMU_2eproto = nullptr;
const ::uint32_t
    TableStruct_FMU_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::FMU_server::Reference, _impl_.ref_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::FMU_server::Reference)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::FMU_server::_Reference_default_instance_._instance,
};
const char descriptor_table_protodef_FMU_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tFMU.proto\022\nFMU_server\032\014villas.proto\"\030\n"
    "\tReference\022\013\n\003ref\030\001 \003(\0052\371\002\n\013FMI_service\022"
    ":\n\nFMU_DoStep\022\024.villas.node.Message\032\024.vi"
    "llas.node.Message\"\000\022;\n\013FMU_GetData\022\024.vil"
    "las.node.Message\032\024.villas.node.Message\"\000"
    "\022;\n\013FMU_SetData\022\024.villas.node.Message\032\024."
    "villas.node.Message\"\000\0228\n\010FMU_GetV\022\024.vill"
    "as.node.Message\032\024.villas.node.Message\"\000\022"
    "9\n\tdata_echo\022\024.villas.node.Message\032\024.vil"
    "las.node.Message\"\000\022\?\n\016FMU_GetDataRef\022\025.F"
    "MU_server.Reference\032\024.villas.node.Messag"
    "e\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_FMU_2eproto_deps[1] = {
        &::descriptor_table_villas_2eproto,
};
static ::absl::once_flag descriptor_table_FMU_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_FMU_2eproto = {
    false,
    false,
    451,
    descriptor_table_protodef_FMU_2eproto,
    "FMU.proto",
    &descriptor_table_FMU_2eproto_once,
    descriptor_table_FMU_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_FMU_2eproto::offsets,
    file_level_enum_descriptors_FMU_2eproto,
    file_level_service_descriptors_FMU_2eproto,
};
namespace FMU_server {
// ===================================================================

class Reference::_Internal {
 public:
};

Reference::Reference(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Reference_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FMU_server.Reference)
}
PROTOBUF_NDEBUG_INLINE Reference::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::FMU_server::Reference& from_msg)
      : ref_{visibility, arena, from.ref_},
        _ref_cached_byte_size_{0},
        _cached_size_{0} {}

Reference::Reference(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Reference& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Reference_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Reference* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:FMU_server.Reference)
}
PROTOBUF_NDEBUG_INLINE Reference::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : ref_{visibility, arena},
        _ref_cached_byte_size_{0},
        _cached_size_{0} {}

inline void Reference::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Reference::~Reference() {
  // @@protoc_insertion_point(destructor:FMU_server.Reference)
  SharedDtor(*this);
}
inline void Reference::SharedDtor(MessageLite& self) {
  Reference& this_ = static_cast<Reference&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Reference::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Reference(arena);
}
constexpr auto Reference::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Reference, _impl_.ref_) +
          decltype(Reference::_impl_.ref_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Reference), alignof(Reference), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Reference::PlacementNew_,
                                 sizeof(Reference),
                                 alignof(Reference));
  }
}
constexpr auto Reference::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Reference_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Reference::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Reference>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Reference::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Reference>(), &Reference::ByteSizeLong,
              &Reference::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Reference, _impl_._cached_size_),
          false,
      },
      &Reference::kDescriptorMethods,
      &descriptor_table_FMU_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Reference_class_data_ =
        Reference::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Reference::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Reference_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Reference_class_data_.tc_table);
  return Reference_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Reference::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Reference_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FMU_server::Reference>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int32 ref = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Reference, _impl_.ref_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 ref = 1;
    {PROTOBUF_FIELD_OFFSET(Reference, _impl_.ref_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Reference::Clear() {
// @@protoc_insertion_point(message_clear_start:FMU_server.Reference)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ref_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Reference::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Reference& this_ = static_cast<const Reference&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Reference::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Reference& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:FMU_server.Reference)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated int32 ref = 1;
  {
    int byte_size = this_._impl_._ref_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, this_._internal_ref(), byte_size, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FMU_server.Reference)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Reference::ByteSizeLong(const MessageLite& base) {
  const Reference& this_ = static_cast<const Reference&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Reference::ByteSizeLong() const {
  const Reference& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:FMU_server.Reference)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated int32 ref = 1;
    {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_ref(), 1,
              this_._impl_._ref_cached_byte_size_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Reference::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Reference*>(&to_msg);
  auto& from = static_cast<const Reference&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FMU_server.Reference)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ref()->MergeFrom(from._internal_ref());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Reference::CopyFrom(const Reference& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FMU_server.Reference)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Reference::InternalSwap(Reference* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ref_.InternalSwap(&other->_impl_.ref_);
}

::google::protobuf::Metadata Reference::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace FMU_server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_FMU_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
