// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FMU.proto

#include "FMU.pb.h"
#include "FMU.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace FMU_server {

static const char* FMI_service_method_names[] = {
  "/FMU_server.FMI_service/FMU_DoStep",
  "/FMU_server.FMI_service/FMU_GetData",
  "/FMU_server.FMI_service/FMU_SetData",
  "/FMU_server.FMI_service/FMU_GetV",
  "/FMU_server.FMI_service/data_echo",
  "/FMU_server.FMI_service/FMU_GetDataRef",
};

std::unique_ptr< FMI_service::Stub> FMI_service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FMI_service::Stub> stub(new FMI_service::Stub(channel, options));
  return stub;
}

FMI_service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_FMU_DoStep_(FMI_service_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FMU_GetData_(FMI_service_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FMU_SetData_(FMI_service_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FMU_GetV_(FMI_service_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_data_echo_(FMI_service_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FMU_GetDataRef_(FMI_service_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FMI_service::Stub::FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FMU_DoStep_, context, request, response);
}

void FMI_service::Stub::async::FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_DoStep_, context, request, response, std::move(f));
}

void FMI_service::Stub::async::FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_DoStep_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::PrepareAsyncFMU_DoStepRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FMU_DoStep_, context, request);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::AsyncFMU_DoStepRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFMU_DoStepRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FMI_service::Stub::FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FMU_GetData_, context, request, response);
}

void FMI_service::Stub::async::FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_GetData_, context, request, response, std::move(f));
}

void FMI_service::Stub::async::FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_GetData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::PrepareAsyncFMU_GetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FMU_GetData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::AsyncFMU_GetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFMU_GetDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FMI_service::Stub::FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FMU_SetData_, context, request, response);
}

void FMI_service::Stub::async::FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_SetData_, context, request, response, std::move(f));
}

void FMI_service::Stub::async::FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_SetData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::PrepareAsyncFMU_SetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FMU_SetData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::AsyncFMU_SetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFMU_SetDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FMI_service::Stub::FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FMU_GetV_, context, request, response);
}

void FMI_service::Stub::async::FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_GetV_, context, request, response, std::move(f));
}

void FMI_service::Stub::async::FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_GetV_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::PrepareAsyncFMU_GetVRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FMU_GetV_, context, request);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::AsyncFMU_GetVRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFMU_GetVRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FMI_service::Stub::data_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_data_echo_, context, request, response);
}

void FMI_service::Stub::async::data_echo(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_data_echo_, context, request, response, std::move(f));
}

void FMI_service::Stub::async::data_echo(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_data_echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::PrepareAsyncdata_echoRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_data_echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::Asyncdata_echoRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdata_echoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FMI_service::Stub::FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::villas::node::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::FMU_server::Reference, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FMU_GetDataRef_, context, request, response);
}

void FMI_service::Stub::async::FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::FMU_server::Reference, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_GetDataRef_, context, request, response, std::move(f));
}

void FMI_service::Stub::async::FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FMU_GetDataRef_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::PrepareAsyncFMU_GetDataRefRaw(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::villas::node::Message, ::FMU_server::Reference, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FMU_GetDataRef_, context, request);
}

::grpc::ClientAsyncResponseReader< ::villas::node::Message>* FMI_service::Stub::AsyncFMU_GetDataRefRaw(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFMU_GetDataRefRaw(context, request, cq);
  result->StartCall();
  return result;
}

FMI_service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FMI_service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FMI_service::Service, ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FMI_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::villas::node::Message* req,
             ::villas::node::Message* resp) {
               return service->FMU_DoStep(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FMI_service_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FMI_service::Service, ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FMI_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::villas::node::Message* req,
             ::villas::node::Message* resp) {
               return service->FMU_GetData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FMI_service_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FMI_service::Service, ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FMI_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::villas::node::Message* req,
             ::villas::node::Message* resp) {
               return service->FMU_SetData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FMI_service_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FMI_service::Service, ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FMI_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::villas::node::Message* req,
             ::villas::node::Message* resp) {
               return service->FMU_GetV(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FMI_service_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FMI_service::Service, ::villas::node::Message, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FMI_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::villas::node::Message* req,
             ::villas::node::Message* resp) {
               return service->data_echo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FMI_service_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FMI_service::Service, ::FMU_server::Reference, ::villas::node::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FMI_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FMU_server::Reference* req,
             ::villas::node::Message* resp) {
               return service->FMU_GetDataRef(ctx, req, resp);
             }, this)));
}

FMI_service::Service::~Service() {
}

::grpc::Status FMI_service::Service::FMU_DoStep(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FMI_service::Service::FMU_GetData(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FMI_service::Service::FMU_SetData(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FMI_service::Service::FMU_GetV(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FMI_service::Service::data_echo(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FMI_service::Service::FMU_GetDataRef(::grpc::ServerContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace FMU_server
#include <grpcpp/ports_undef.inc>

