// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: villas.proto
// Protobuf C++ Version: 6.31.0

#ifndef villas_2eproto_2epb_2eh
#define villas_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_villas_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_villas_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_villas_2eproto;
}  // extern "C"
namespace villas {
namespace node {
enum Sample_Type : int;
extern const uint32_t Sample_Type_internal_data_[];
class Complex;
struct ComplexDefaultTypeInternal;
extern ComplexDefaultTypeInternal _Complex_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Complex_class_data_;
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Message_class_data_;
class Sample;
struct SampleDefaultTypeInternal;
extern SampleDefaultTypeInternal _Sample_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Sample_class_data_;
class Timestamp;
struct TimestampDefaultTypeInternal;
extern TimestampDefaultTypeInternal _Timestamp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Timestamp_class_data_;
class Value;
struct ValueDefaultTypeInternal;
extern ValueDefaultTypeInternal _Value_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Value_class_data_;
}  // namespace node
}  // namespace villas
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::villas::node::Sample_Type_internal_data_>
    internal::EnumTraitsImpl::value<::villas::node::Sample_Type>;
}  // namespace protobuf
}  // namespace google

namespace villas {
namespace node {
enum Sample_Type : int {
  Sample_Type_DATA = 1,
  Sample_Type_START = 2,
  Sample_Type_STOP = 3,
};

extern const uint32_t Sample_Type_internal_data_[];
inline constexpr Sample_Type Sample_Type_Type_MIN =
    static_cast<Sample_Type>(1);
inline constexpr Sample_Type Sample_Type_Type_MAX =
    static_cast<Sample_Type>(3);
inline bool Sample_Type_IsValid(int value) {
  return 1 <= value && value <= 3;
}
inline constexpr int Sample_Type_Type_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Sample_Type_descriptor();
template <typename T>
const ::std::string& Sample_Type_Name(T value) {
  static_assert(::std::is_same<T, Sample_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return Sample_Type_Name(static_cast<Sample_Type>(value));
}
template <>
inline const ::std::string& Sample_Type_Name(Sample_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Sample_Type_descriptor, 1, 3>(
      static_cast<int>(value));
}
inline bool Sample_Type_Parse(
    ::absl::string_view name, Sample_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Sample_Type>(Sample_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Timestamp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:villas.node.Timestamp) */ {
 public:
  inline Timestamp() : Timestamp(nullptr) {}
  ~Timestamp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Timestamp* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Timestamp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Timestamp(::google::protobuf::internal::ConstantInitialized);

  inline Timestamp(const Timestamp& from) : Timestamp(nullptr, from) {}
  inline Timestamp(Timestamp&& from) noexcept
      : Timestamp(nullptr, ::std::move(from)) {}
  inline Timestamp& operator=(const Timestamp& from) {
    CopyFrom(from);
    return *this;
  }
  inline Timestamp& operator=(Timestamp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Timestamp& default_instance() {
    return *reinterpret_cast<const Timestamp*>(
        &_Timestamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Timestamp& a, Timestamp& b) { a.Swap(&b); }
  inline void Swap(Timestamp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Timestamp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Timestamp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Timestamp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Timestamp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Timestamp& from) { Timestamp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Timestamp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "villas.node.Timestamp"; }

 protected:
  explicit Timestamp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Timestamp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Timestamp& from);
  Timestamp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Timestamp&& from) noexcept
      : Timestamp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSecFieldNumber = 1,
    kNsecFieldNumber = 2,
  };
  // required uint32 sec = 1;
  bool has_sec() const;
  void clear_sec() ;
  ::uint32_t sec() const;
  void set_sec(::uint32_t value);

  private:
  ::uint32_t _internal_sec() const;
  void _internal_set_sec(::uint32_t value);

  public:
  // required uint32 nsec = 2;
  bool has_nsec() const;
  void clear_nsec() ;
  ::uint32_t nsec() const;
  void set_nsec(::uint32_t value);

  private:
  ::uint32_t _internal_nsec() const;
  void _internal_set_nsec(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:villas.node.Timestamp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Timestamp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t sec_;
    ::uint32_t nsec_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_villas_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Timestamp_class_data_;
// -------------------------------------------------------------------

class Complex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:villas.node.Complex) */ {
 public:
  inline Complex() : Complex(nullptr) {}
  ~Complex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Complex* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Complex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Complex(::google::protobuf::internal::ConstantInitialized);

  inline Complex(const Complex& from) : Complex(nullptr, from) {}
  inline Complex(Complex&& from) noexcept
      : Complex(nullptr, ::std::move(from)) {}
  inline Complex& operator=(const Complex& from) {
    CopyFrom(from);
    return *this;
  }
  inline Complex& operator=(Complex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Complex& default_instance() {
    return *reinterpret_cast<const Complex*>(
        &_Complex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Complex& a, Complex& b) { a.Swap(&b); }
  inline void Swap(Complex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Complex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Complex* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Complex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Complex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Complex& from) { Complex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Complex* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "villas.node.Complex"; }

 protected:
  explicit Complex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Complex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Complex& from);
  Complex(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Complex&& from) noexcept
      : Complex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRealFieldNumber = 1,
    kImagFieldNumber = 2,
  };
  // required float real = 1;
  bool has_real() const;
  void clear_real() ;
  float real() const;
  void set_real(float value);

  private:
  float _internal_real() const;
  void _internal_set_real(float value);

  public:
  // required float imag = 2;
  bool has_imag() const;
  void clear_imag() ;
  float imag() const;
  void set_imag(float value);

  private:
  float _internal_imag() const;
  void _internal_set_imag(float value);

  public:
  // @@protoc_insertion_point(class_scope:villas.node.Complex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Complex& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float real_;
    float imag_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_villas_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Complex_class_data_;
// -------------------------------------------------------------------

class Value final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:villas.node.Value) */ {
 public:
  inline Value() : Value(nullptr) {}
  ~Value() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Value* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Value));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Value(::google::protobuf::internal::ConstantInitialized);

  inline Value(const Value& from) : Value(nullptr, from) {}
  inline Value(Value&& from) noexcept
      : Value(nullptr, ::std::move(from)) {}
  inline Value& operator=(const Value& from) {
    CopyFrom(from);
    return *this;
  }
  inline Value& operator=(Value&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Value& default_instance() {
    return *reinterpret_cast<const Value*>(
        &_Value_default_instance_);
  }
  enum ValueCase {
    kF = 1,
    kI = 2,
    kB = 3,
    kZ = 4,
    VALUE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Value& a, Value& b) { a.Swap(&b); }
  inline void Swap(Value* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Value* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Value* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Value>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Value& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Value& from) { Value::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Value* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "villas.node.Value"; }

 protected:
  explicit Value(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Value(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Value& from);
  Value(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Value&& from) noexcept
      : Value(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFFieldNumber = 1,
    kIFieldNumber = 2,
    kBFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // double f = 1;
  bool has_f() const;
  void clear_f() ;
  double f() const;
  void set_f(double value);

  private:
  double _internal_f() const;
  void _internal_set_f(double value);

  public:
  // int64 i = 2;
  bool has_i() const;
  void clear_i() ;
  ::int64_t i() const;
  void set_i(::int64_t value);

  private:
  ::int64_t _internal_i() const;
  void _internal_set_i(::int64_t value);

  public:
  // bool b = 3;
  bool has_b() const;
  void clear_b() ;
  bool b() const;
  void set_b(bool value);

  private:
  bool _internal_b() const;
  void _internal_set_b(bool value);

  public:
  // .villas.node.Complex z = 4;
  bool has_z() const;
  private:
  bool _internal_has_z() const;

  public:
  void clear_z() ;
  const ::villas::node::Complex& z() const;
  [[nodiscard]] ::villas::node::Complex* PROTOBUF_NULLABLE release_z();
  ::villas::node::Complex* PROTOBUF_NONNULL mutable_z();
  void set_allocated_z(::villas::node::Complex* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_z(::villas::node::Complex* PROTOBUF_NULLABLE value);
  ::villas::node::Complex* PROTOBUF_NULLABLE unsafe_arena_release_z();

  private:
  const ::villas::node::Complex& _internal_z() const;
  ::villas::node::Complex* PROTOBUF_NONNULL _internal_mutable_z();

  public:
  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:villas.node.Value)
 private:
  class _Internal;
  void set_has_f();
  void set_has_i();
  void set_has_b();
  void set_has_z();
  inline bool has_value() const;
  inline void clear_has_value();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Value& from_msg);
    union ValueUnion {
      constexpr ValueUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      double f_;
      ::int64_t i_;
      bool b_;
      ::villas::node::Complex* PROTOBUF_NULLABLE z_;
    } value_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_villas_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Value_class_data_;
// -------------------------------------------------------------------

class Sample final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:villas.node.Sample) */ {
 public:
  inline Sample() : Sample(nullptr) {}
  ~Sample() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Sample* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Sample));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Sample(::google::protobuf::internal::ConstantInitialized);

  inline Sample(const Sample& from) : Sample(nullptr, from) {}
  inline Sample(Sample&& from) noexcept
      : Sample(nullptr, ::std::move(from)) {}
  inline Sample& operator=(const Sample& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sample& operator=(Sample&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Sample& default_instance() {
    return *reinterpret_cast<const Sample*>(
        &_Sample_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Sample& a, Sample& b) { a.Swap(&b); }
  inline void Swap(Sample* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sample* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Sample* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Sample>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Sample& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Sample& from) { Sample::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Sample* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "villas.node.Sample"; }

 protected:
  explicit Sample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Sample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Sample& from);
  Sample(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Sample&& from) noexcept
      : Sample(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = Sample_Type;
  static constexpr Type DATA = Sample_Type_DATA;
  static constexpr Type START = Sample_Type_START;
  static constexpr Type STOP = Sample_Type_STOP;
  static inline bool Type_IsValid(int value) {
    return Sample_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = Sample_Type_Type_MIN;
  static constexpr Type Type_MAX = Sample_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = Sample_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return Sample_Type_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Type_Name(T value) {
    return Sample_Type_Name(value);
  }
  static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return Sample_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 100,
    kTsOriginFieldNumber = 3,
    kTsReceivedFieldNumber = 4,
    kSequenceFieldNumber = 2,
    kNewFrameFieldNumber = 5,
    kTypeFieldNumber = 1,
  };
  // repeated .villas.node.Value values = 100;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  ::villas::node::Value* PROTOBUF_NONNULL mutable_values(int index);
  ::google::protobuf::RepeatedPtrField<::villas::node::Value>* PROTOBUF_NONNULL mutable_values();

  private:
  const ::google::protobuf::RepeatedPtrField<::villas::node::Value>& _internal_values() const;
  ::google::protobuf::RepeatedPtrField<::villas::node::Value>* PROTOBUF_NONNULL _internal_mutable_values();
  public:
  const ::villas::node::Value& values(int index) const;
  ::villas::node::Value* PROTOBUF_NONNULL add_values();
  const ::google::protobuf::RepeatedPtrField<::villas::node::Value>& values() const;
  // optional .villas.node.Timestamp ts_origin = 3;
  bool has_ts_origin() const;
  void clear_ts_origin() ;
  const ::villas::node::Timestamp& ts_origin() const;
  [[nodiscard]] ::villas::node::Timestamp* PROTOBUF_NULLABLE release_ts_origin();
  ::villas::node::Timestamp* PROTOBUF_NONNULL mutable_ts_origin();
  void set_allocated_ts_origin(::villas::node::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ts_origin(::villas::node::Timestamp* PROTOBUF_NULLABLE value);
  ::villas::node::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_ts_origin();

  private:
  const ::villas::node::Timestamp& _internal_ts_origin() const;
  ::villas::node::Timestamp* PROTOBUF_NONNULL _internal_mutable_ts_origin();

  public:
  // optional .villas.node.Timestamp ts_received = 4;
  bool has_ts_received() const;
  void clear_ts_received() ;
  const ::villas::node::Timestamp& ts_received() const;
  [[nodiscard]] ::villas::node::Timestamp* PROTOBUF_NULLABLE release_ts_received();
  ::villas::node::Timestamp* PROTOBUF_NONNULL mutable_ts_received();
  void set_allocated_ts_received(::villas::node::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ts_received(::villas::node::Timestamp* PROTOBUF_NULLABLE value);
  ::villas::node::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_ts_received();

  private:
  const ::villas::node::Timestamp& _internal_ts_received() const;
  ::villas::node::Timestamp* PROTOBUF_NONNULL _internal_mutable_ts_received();

  public:
  // optional uint64 sequence = 2;
  bool has_sequence() const;
  void clear_sequence() ;
  ::uint64_t sequence() const;
  void set_sequence(::uint64_t value);

  private:
  ::uint64_t _internal_sequence() const;
  void _internal_set_sequence(::uint64_t value);

  public:
  // optional bool new_frame = 5;
  bool has_new_frame() const;
  void clear_new_frame() ;
  bool new_frame() const;
  void set_new_frame(bool value);

  private:
  bool _internal_new_frame() const;
  void _internal_set_new_frame(bool value);

  public:
  // required .villas.node.Sample.Type type = 1 [default = DATA];
  bool has_type() const;
  void clear_type() ;
  ::villas::node::Sample_Type type() const;
  void set_type(::villas::node::Sample_Type value);

  private:
  ::villas::node::Sample_Type _internal_type() const;
  void _internal_set_type(::villas::node::Sample_Type value);

  public:
  // @@protoc_insertion_point(class_scope:villas.node.Sample)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   4, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Sample& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::villas::node::Value > values_;
    ::villas::node::Timestamp* PROTOBUF_NULLABLE ts_origin_;
    ::villas::node::Timestamp* PROTOBUF_NULLABLE ts_received_;
    ::uint64_t sequence_;
    bool new_frame_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_villas_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Sample_class_data_;
// -------------------------------------------------------------------

class Message final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:villas.node.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Message* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Message));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Message(::google::protobuf::internal::ConstantInitialized);

  inline Message(const Message& from) : Message(nullptr, from) {}
  inline Message(Message&& from) noexcept
      : Message(nullptr, ::std::move(from)) {}
  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *reinterpret_cast<const Message*>(
        &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Message& a, Message& b) { a.Swap(&b); }
  inline void Swap(Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Message>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Message& from) { Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "villas.node.Message"; }

 protected:
  explicit Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Message& from);
  Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Message&& from) noexcept
      : Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSamplesFieldNumber = 1,
  };
  // repeated .villas.node.Sample samples = 1;
  int samples_size() const;
  private:
  int _internal_samples_size() const;

  public:
  void clear_samples() ;
  ::villas::node::Sample* PROTOBUF_NONNULL mutable_samples(int index);
  ::google::protobuf::RepeatedPtrField<::villas::node::Sample>* PROTOBUF_NONNULL mutable_samples();

  private:
  const ::google::protobuf::RepeatedPtrField<::villas::node::Sample>& _internal_samples() const;
  ::google::protobuf::RepeatedPtrField<::villas::node::Sample>* PROTOBUF_NONNULL _internal_mutable_samples();
  public:
  const ::villas::node::Sample& samples(int index) const;
  ::villas::node::Sample* PROTOBUF_NONNULL add_samples();
  const ::google::protobuf::RepeatedPtrField<::villas::node::Sample>& samples() const;
  // @@protoc_insertion_point(class_scope:villas.node.Message)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Message& from_msg);
    ::google::protobuf::RepeatedPtrField< ::villas::node::Sample > samples_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_villas_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Message_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Message

// repeated .villas.node.Sample samples = 1;
inline int Message::_internal_samples_size() const {
  return _internal_samples().size();
}
inline int Message::samples_size() const {
  return _internal_samples_size();
}
inline void Message::clear_samples() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.samples_.Clear();
}
inline ::villas::node::Sample* PROTOBUF_NONNULL Message::mutable_samples(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:villas.node.Message.samples)
  return _internal_mutable_samples()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::villas::node::Sample>* PROTOBUF_NONNULL Message::mutable_samples()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:villas.node.Message.samples)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_samples();
}
inline const ::villas::node::Sample& Message::samples(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:villas.node.Message.samples)
  return _internal_samples().Get(index);
}
inline ::villas::node::Sample* PROTOBUF_NONNULL Message::add_samples()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::villas::node::Sample* _add = _internal_mutable_samples()->Add();
  // @@protoc_insertion_point(field_add:villas.node.Message.samples)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::villas::node::Sample>& Message::samples() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:villas.node.Message.samples)
  return _internal_samples();
}
inline const ::google::protobuf::RepeatedPtrField<::villas::node::Sample>&
Message::_internal_samples() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.samples_;
}
inline ::google::protobuf::RepeatedPtrField<::villas::node::Sample>* PROTOBUF_NONNULL
Message::_internal_mutable_samples() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.samples_;
}

// -------------------------------------------------------------------

// Sample

// required .villas.node.Sample.Type type = 1 [default = DATA];
inline bool Sample::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Sample::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 1;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::villas::node::Sample_Type Sample::type() const {
  // @@protoc_insertion_point(field_get:villas.node.Sample.type)
  return _internal_type();
}
inline void Sample::set_type(::villas::node::Sample_Type value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:villas.node.Sample.type)
}
inline ::villas::node::Sample_Type Sample::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::villas::node::Sample_Type>(_impl_.type_);
}
inline void Sample::_internal_set_type(::villas::node::Sample_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::villas::node::Sample_Type_internal_data_));
                                          _impl_.type_ = value;
}

// optional uint64 sequence = 2;
inline bool Sample::has_sequence() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Sample::clear_sequence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint64_t Sample::sequence() const {
  // @@protoc_insertion_point(field_get:villas.node.Sample.sequence)
  return _internal_sequence();
}
inline void Sample::set_sequence(::uint64_t value) {
  _internal_set_sequence(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:villas.node.Sample.sequence)
}
inline ::uint64_t Sample::_internal_sequence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_;
}
inline void Sample::_internal_set_sequence(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_ = value;
}

// optional .villas.node.Timestamp ts_origin = 3;
inline bool Sample::has_ts_origin() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.ts_origin_ != nullptr);
  return value;
}
inline void Sample::clear_ts_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ts_origin_ != nullptr) _impl_.ts_origin_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::villas::node::Timestamp& Sample::_internal_ts_origin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::villas::node::Timestamp* p = _impl_.ts_origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::villas::node::Timestamp&>(::villas::node::_Timestamp_default_instance_);
}
inline const ::villas::node::Timestamp& Sample::ts_origin() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:villas.node.Sample.ts_origin)
  return _internal_ts_origin();
}
inline void Sample::unsafe_arena_set_allocated_ts_origin(
    ::villas::node::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ts_origin_);
  }
  _impl_.ts_origin_ = reinterpret_cast<::villas::node::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:villas.node.Sample.ts_origin)
}
inline ::villas::node::Timestamp* PROTOBUF_NULLABLE Sample::release_ts_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::villas::node::Timestamp* released = _impl_.ts_origin_;
  _impl_.ts_origin_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::villas::node::Timestamp* PROTOBUF_NULLABLE Sample::unsafe_arena_release_ts_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:villas.node.Sample.ts_origin)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::villas::node::Timestamp* temp = _impl_.ts_origin_;
  _impl_.ts_origin_ = nullptr;
  return temp;
}
inline ::villas::node::Timestamp* PROTOBUF_NONNULL Sample::_internal_mutable_ts_origin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ts_origin_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::villas::node::Timestamp>(GetArena());
    _impl_.ts_origin_ = reinterpret_cast<::villas::node::Timestamp*>(p);
  }
  return _impl_.ts_origin_;
}
inline ::villas::node::Timestamp* PROTOBUF_NONNULL Sample::mutable_ts_origin()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::villas::node::Timestamp* _msg = _internal_mutable_ts_origin();
  // @@protoc_insertion_point(field_mutable:villas.node.Sample.ts_origin)
  return _msg;
}
inline void Sample::set_allocated_ts_origin(::villas::node::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ts_origin_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.ts_origin_ = reinterpret_cast<::villas::node::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:villas.node.Sample.ts_origin)
}

// optional .villas.node.Timestamp ts_received = 4;
inline bool Sample::has_ts_received() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.ts_received_ != nullptr);
  return value;
}
inline void Sample::clear_ts_received() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ts_received_ != nullptr) _impl_.ts_received_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::villas::node::Timestamp& Sample::_internal_ts_received() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::villas::node::Timestamp* p = _impl_.ts_received_;
  return p != nullptr ? *p : reinterpret_cast<const ::villas::node::Timestamp&>(::villas::node::_Timestamp_default_instance_);
}
inline const ::villas::node::Timestamp& Sample::ts_received() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:villas.node.Sample.ts_received)
  return _internal_ts_received();
}
inline void Sample::unsafe_arena_set_allocated_ts_received(
    ::villas::node::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ts_received_);
  }
  _impl_.ts_received_ = reinterpret_cast<::villas::node::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:villas.node.Sample.ts_received)
}
inline ::villas::node::Timestamp* PROTOBUF_NULLABLE Sample::release_ts_received() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::villas::node::Timestamp* released = _impl_.ts_received_;
  _impl_.ts_received_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::villas::node::Timestamp* PROTOBUF_NULLABLE Sample::unsafe_arena_release_ts_received() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:villas.node.Sample.ts_received)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::villas::node::Timestamp* temp = _impl_.ts_received_;
  _impl_.ts_received_ = nullptr;
  return temp;
}
inline ::villas::node::Timestamp* PROTOBUF_NONNULL Sample::_internal_mutable_ts_received() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ts_received_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::villas::node::Timestamp>(GetArena());
    _impl_.ts_received_ = reinterpret_cast<::villas::node::Timestamp*>(p);
  }
  return _impl_.ts_received_;
}
inline ::villas::node::Timestamp* PROTOBUF_NONNULL Sample::mutable_ts_received()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::villas::node::Timestamp* _msg = _internal_mutable_ts_received();
  // @@protoc_insertion_point(field_mutable:villas.node.Sample.ts_received)
  return _msg;
}
inline void Sample::set_allocated_ts_received(::villas::node::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ts_received_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.ts_received_ = reinterpret_cast<::villas::node::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:villas.node.Sample.ts_received)
}

// optional bool new_frame = 5;
inline bool Sample::has_new_frame() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Sample::clear_new_frame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_frame_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool Sample::new_frame() const {
  // @@protoc_insertion_point(field_get:villas.node.Sample.new_frame)
  return _internal_new_frame();
}
inline void Sample::set_new_frame(bool value) {
  _internal_set_new_frame(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:villas.node.Sample.new_frame)
}
inline bool Sample::_internal_new_frame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.new_frame_;
}
inline void Sample::_internal_set_new_frame(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_frame_ = value;
}

// repeated .villas.node.Value values = 100;
inline int Sample::_internal_values_size() const {
  return _internal_values().size();
}
inline int Sample::values_size() const {
  return _internal_values_size();
}
inline void Sample::clear_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.values_.Clear();
}
inline ::villas::node::Value* PROTOBUF_NONNULL Sample::mutable_values(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:villas.node.Sample.values)
  return _internal_mutable_values()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::villas::node::Value>* PROTOBUF_NONNULL Sample::mutable_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:villas.node.Sample.values)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_values();
}
inline const ::villas::node::Value& Sample::values(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:villas.node.Sample.values)
  return _internal_values().Get(index);
}
inline ::villas::node::Value* PROTOBUF_NONNULL Sample::add_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::villas::node::Value* _add = _internal_mutable_values()->Add();
  // @@protoc_insertion_point(field_add:villas.node.Sample.values)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::villas::node::Value>& Sample::values() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:villas.node.Sample.values)
  return _internal_values();
}
inline const ::google::protobuf::RepeatedPtrField<::villas::node::Value>&
Sample::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_;
}
inline ::google::protobuf::RepeatedPtrField<::villas::node::Value>* PROTOBUF_NONNULL
Sample::_internal_mutable_values() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.values_;
}

// -------------------------------------------------------------------

// Timestamp

// required uint32 sec = 1;
inline bool Timestamp::has_sec() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Timestamp::clear_sec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sec_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t Timestamp::sec() const {
  // @@protoc_insertion_point(field_get:villas.node.Timestamp.sec)
  return _internal_sec();
}
inline void Timestamp::set_sec(::uint32_t value) {
  _internal_set_sec(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:villas.node.Timestamp.sec)
}
inline ::uint32_t Timestamp::_internal_sec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sec_;
}
inline void Timestamp::_internal_set_sec(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sec_ = value;
}

// required uint32 nsec = 2;
inline bool Timestamp::has_nsec() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Timestamp::clear_nsec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nsec_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t Timestamp::nsec() const {
  // @@protoc_insertion_point(field_get:villas.node.Timestamp.nsec)
  return _internal_nsec();
}
inline void Timestamp::set_nsec(::uint32_t value) {
  _internal_set_nsec(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:villas.node.Timestamp.nsec)
}
inline ::uint32_t Timestamp::_internal_nsec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nsec_;
}
inline void Timestamp::_internal_set_nsec(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nsec_ = value;
}

// -------------------------------------------------------------------

// Value

// double f = 1;
inline bool Value::has_f() const {
  return value_case() == kF;
}
inline void Value::set_has_f() {
  _impl_._oneof_case_[0] = kF;
}
inline void Value::clear_f() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kF) {
    _impl_.value_.f_ = 0;
    clear_has_value();
  }
}
inline double Value::f() const {
  // @@protoc_insertion_point(field_get:villas.node.Value.f)
  return _internal_f();
}
inline void Value::set_f(double value) {
  if (value_case() != kF) {
    clear_value();
    set_has_f();
  }
  _impl_.value_.f_ = value;
  // @@protoc_insertion_point(field_set:villas.node.Value.f)
}
inline double Value::_internal_f() const {
  if (value_case() == kF) {
    return _impl_.value_.f_;
  }
  return 0;
}

// int64 i = 2;
inline bool Value::has_i() const {
  return value_case() == kI;
}
inline void Value::set_has_i() {
  _impl_._oneof_case_[0] = kI;
}
inline void Value::clear_i() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kI) {
    _impl_.value_.i_ = ::int64_t{0};
    clear_has_value();
  }
}
inline ::int64_t Value::i() const {
  // @@protoc_insertion_point(field_get:villas.node.Value.i)
  return _internal_i();
}
inline void Value::set_i(::int64_t value) {
  if (value_case() != kI) {
    clear_value();
    set_has_i();
  }
  _impl_.value_.i_ = value;
  // @@protoc_insertion_point(field_set:villas.node.Value.i)
}
inline ::int64_t Value::_internal_i() const {
  if (value_case() == kI) {
    return _impl_.value_.i_;
  }
  return ::int64_t{0};
}

// bool b = 3;
inline bool Value::has_b() const {
  return value_case() == kB;
}
inline void Value::set_has_b() {
  _impl_._oneof_case_[0] = kB;
}
inline void Value::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kB) {
    _impl_.value_.b_ = false;
    clear_has_value();
  }
}
inline bool Value::b() const {
  // @@protoc_insertion_point(field_get:villas.node.Value.b)
  return _internal_b();
}
inline void Value::set_b(bool value) {
  if (value_case() != kB) {
    clear_value();
    set_has_b();
  }
  _impl_.value_.b_ = value;
  // @@protoc_insertion_point(field_set:villas.node.Value.b)
}
inline bool Value::_internal_b() const {
  if (value_case() == kB) {
    return _impl_.value_.b_;
  }
  return false;
}

// .villas.node.Complex z = 4;
inline bool Value::has_z() const {
  return value_case() == kZ;
}
inline bool Value::_internal_has_z() const {
  return value_case() == kZ;
}
inline void Value::set_has_z() {
  _impl_._oneof_case_[0] = kZ;
}
inline void Value::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kZ) {
    if (GetArena() == nullptr) {
      delete _impl_.value_.z_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.z_);
    }
    clear_has_value();
  }
}
inline ::villas::node::Complex* PROTOBUF_NULLABLE Value::release_z() {
  // @@protoc_insertion_point(field_release:villas.node.Value.z)
  if (value_case() == kZ) {
    clear_has_value();
    auto* temp = _impl_.value_.z_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.value_.z_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::villas::node::Complex& Value::_internal_z() const {
  return value_case() == kZ ? *_impl_.value_.z_ : reinterpret_cast<::villas::node::Complex&>(::villas::node::_Complex_default_instance_);
}
inline const ::villas::node::Complex& Value::z() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:villas.node.Value.z)
  return _internal_z();
}
inline ::villas::node::Complex* PROTOBUF_NULLABLE Value::unsafe_arena_release_z() {
  // @@protoc_insertion_point(field_unsafe_arena_release:villas.node.Value.z)
  if (value_case() == kZ) {
    clear_has_value();
    auto* temp = _impl_.value_.z_;
    _impl_.value_.z_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Value::unsafe_arena_set_allocated_z(
    ::villas::node::Complex* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_value();
  if (value) {
    set_has_z();
    _impl_.value_.z_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:villas.node.Value.z)
}
inline ::villas::node::Complex* PROTOBUF_NONNULL Value::_internal_mutable_z() {
  if (value_case() != kZ) {
    clear_value();
    set_has_z();
    _impl_.value_.z_ = 
        ::google::protobuf::Message::DefaultConstruct<::villas::node::Complex>(GetArena());
  }
  return _impl_.value_.z_;
}
inline ::villas::node::Complex* PROTOBUF_NONNULL Value::mutable_z()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::villas::node::Complex* _msg = _internal_mutable_z();
  // @@protoc_insertion_point(field_mutable:villas.node.Value.z)
  return _msg;
}

inline bool Value::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void Value::clear_has_value() {
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}
inline Value::ValueCase Value::value_case() const {
  return Value::ValueCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Complex

// required float real = 1;
inline bool Complex::has_real() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Complex::clear_real() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.real_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float Complex::real() const {
  // @@protoc_insertion_point(field_get:villas.node.Complex.real)
  return _internal_real();
}
inline void Complex::set_real(float value) {
  _internal_set_real(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:villas.node.Complex.real)
}
inline float Complex::_internal_real() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.real_;
}
inline void Complex::_internal_set_real(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.real_ = value;
}

// required float imag = 2;
inline bool Complex::has_imag() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Complex::clear_imag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imag_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float Complex::imag() const {
  // @@protoc_insertion_point(field_get:villas.node.Complex.imag)
  return _internal_imag();
}
inline void Complex::set_imag(float value) {
  _internal_set_imag(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:villas.node.Complex.imag)
}
inline float Complex::_internal_imag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.imag_;
}
inline void Complex::_internal_set_imag(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imag_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace node
}  // namespace villas


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::villas::node::Sample_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::villas::node::Sample_Type>() {
  return ::villas::node::Sample_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // villas_2eproto_2epb_2eh
