// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FMU.proto
#ifndef GRPC_FMU_2eproto__INCLUDED
#define GRPC_FMU_2eproto__INCLUDED

#include "FMU.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace FMU_server {

class FMI_service final {
 public:
  static constexpr char const* service_full_name() {
    return "FMU_server.FMI_service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> AsyncFMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(AsyncFMU_DoStepRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> PrepareAsyncFMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(PrepareAsyncFMU_DoStepRaw(context, request, cq));
    }
    virtual ::grpc::Status FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> AsyncFMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(AsyncFMU_GetDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> PrepareAsyncFMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(PrepareAsyncFMU_GetDataRaw(context, request, cq));
    }
    virtual ::grpc::Status FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> AsyncFMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(AsyncFMU_SetDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> PrepareAsyncFMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(PrepareAsyncFMU_SetDataRaw(context, request, cq));
    }
    virtual ::grpc::Status FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> AsyncFMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(AsyncFMU_GetVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> PrepareAsyncFMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(PrepareAsyncFMU_GetVRaw(context, request, cq));
    }
    virtual ::grpc::Status data_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> Asyncdata_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(Asyncdata_echoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> PrepareAsyncdata_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(PrepareAsyncdata_echoRaw(context, request, cq));
    }
    virtual ::grpc::Status FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::villas::node::Message* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> AsyncFMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(AsyncFMU_GetDataRefRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>> PrepareAsyncFMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>>(PrepareAsyncFMU_GetDataRefRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void data_echo(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) = 0;
      virtual void data_echo(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* AsyncFMU_DoStepRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* PrepareAsyncFMU_DoStepRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* AsyncFMU_GetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* PrepareAsyncFMU_GetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* AsyncFMU_SetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* PrepareAsyncFMU_SetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* AsyncFMU_GetVRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* PrepareAsyncFMU_GetVRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* Asyncdata_echoRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* PrepareAsyncdata_echoRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* AsyncFMU_GetDataRefRaw(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::villas::node::Message>* PrepareAsyncFMU_GetDataRefRaw(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> AsyncFMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(AsyncFMU_DoStepRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> PrepareAsyncFMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(PrepareAsyncFMU_DoStepRaw(context, request, cq));
    }
    ::grpc::Status FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> AsyncFMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(AsyncFMU_GetDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> PrepareAsyncFMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(PrepareAsyncFMU_GetDataRaw(context, request, cq));
    }
    ::grpc::Status FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> AsyncFMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(AsyncFMU_SetDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> PrepareAsyncFMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(PrepareAsyncFMU_SetDataRaw(context, request, cq));
    }
    ::grpc::Status FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> AsyncFMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(AsyncFMU_GetVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> PrepareAsyncFMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(PrepareAsyncFMU_GetVRaw(context, request, cq));
    }
    ::grpc::Status data_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::villas::node::Message* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> Asyncdata_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(Asyncdata_echoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> PrepareAsyncdata_echo(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(PrepareAsyncdata_echoRaw(context, request, cq));
    }
    ::grpc::Status FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::villas::node::Message* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> AsyncFMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(AsyncFMU_GetDataRefRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>> PrepareAsyncFMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::villas::node::Message>>(PrepareAsyncFMU_GetDataRefRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) override;
      void FMU_DoStep(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) override;
      void FMU_GetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) override;
      void FMU_SetData(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) override;
      void FMU_GetV(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) override;
      void data_echo(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) override;
      void data_echo(::grpc::ClientContext* context, const ::villas::node::Message* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response, std::function<void(::grpc::Status)>) override;
      void FMU_GetDataRef(::grpc::ClientContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* AsyncFMU_DoStepRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* PrepareAsyncFMU_DoStepRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* AsyncFMU_GetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* PrepareAsyncFMU_GetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* AsyncFMU_SetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* PrepareAsyncFMU_SetDataRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* AsyncFMU_GetVRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* PrepareAsyncFMU_GetVRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* Asyncdata_echoRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* PrepareAsyncdata_echoRaw(::grpc::ClientContext* context, const ::villas::node::Message& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* AsyncFMU_GetDataRefRaw(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::villas::node::Message>* PrepareAsyncFMU_GetDataRefRaw(::grpc::ClientContext* context, const ::FMU_server::Reference& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FMU_DoStep_;
    const ::grpc::internal::RpcMethod rpcmethod_FMU_GetData_;
    const ::grpc::internal::RpcMethod rpcmethod_FMU_SetData_;
    const ::grpc::internal::RpcMethod rpcmethod_FMU_GetV_;
    const ::grpc::internal::RpcMethod rpcmethod_data_echo_;
    const ::grpc::internal::RpcMethod rpcmethod_FMU_GetDataRef_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FMU_DoStep(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response);
    virtual ::grpc::Status FMU_GetData(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response);
    virtual ::grpc::Status FMU_SetData(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response);
    virtual ::grpc::Status FMU_GetV(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response);
    virtual ::grpc::Status data_echo(::grpc::ServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response);
    virtual ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FMU_DoStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FMU_DoStep() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FMU_DoStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_DoStep(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_DoStep(::grpc::ServerContext* context, ::villas::node::Message* request, ::grpc::ServerAsyncResponseWriter< ::villas::node::Message>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FMU_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FMU_GetData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FMU_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_GetData(::grpc::ServerContext* context, ::villas::node::Message* request, ::grpc::ServerAsyncResponseWriter< ::villas::node::Message>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FMU_SetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FMU_SetData() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_FMU_SetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_SetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_SetData(::grpc::ServerContext* context, ::villas::node::Message* request, ::grpc::ServerAsyncResponseWriter< ::villas::node::Message>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FMU_GetV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FMU_GetV() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_FMU_GetV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetV(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_GetV(::grpc::ServerContext* context, ::villas::node::Message* request, ::grpc::ServerAsyncResponseWriter< ::villas::node::Message>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_data_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_data_echo() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_data_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status data_echo(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdata_echo(::grpc::ServerContext* context, ::villas::node::Message* request, ::grpc::ServerAsyncResponseWriter< ::villas::node::Message>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FMU_GetDataRef : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FMU_GetDataRef() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_FMU_GetDataRef() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_GetDataRef(::grpc::ServerContext* context, ::FMU_server::Reference* request, ::grpc::ServerAsyncResponseWriter< ::villas::node::Message>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FMU_DoStep<WithAsyncMethod_FMU_GetData<WithAsyncMethod_FMU_SetData<WithAsyncMethod_FMU_GetV<WithAsyncMethod_data_echo<WithAsyncMethod_FMU_GetDataRef<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_FMU_DoStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FMU_DoStep() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) { return this->FMU_DoStep(context, request, response); }));}
    void SetMessageAllocatorFor_FMU_DoStep(
        ::grpc::MessageAllocator< ::villas::node::Message, ::villas::node::Message>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FMU_DoStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_DoStep(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_DoStep(
      ::grpc::CallbackServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FMU_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FMU_GetData() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) { return this->FMU_GetData(context, request, response); }));}
    void SetMessageAllocatorFor_FMU_GetData(
        ::grpc::MessageAllocator< ::villas::node::Message, ::villas::node::Message>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FMU_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_GetData(
      ::grpc::CallbackServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FMU_SetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FMU_SetData() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) { return this->FMU_SetData(context, request, response); }));}
    void SetMessageAllocatorFor_FMU_SetData(
        ::grpc::MessageAllocator< ::villas::node::Message, ::villas::node::Message>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FMU_SetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_SetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_SetData(
      ::grpc::CallbackServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FMU_GetV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FMU_GetV() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) { return this->FMU_GetV(context, request, response); }));}
    void SetMessageAllocatorFor_FMU_GetV(
        ::grpc::MessageAllocator< ::villas::node::Message, ::villas::node::Message>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FMU_GetV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetV(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_GetV(
      ::grpc::CallbackServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_data_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_data_echo() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::villas::node::Message* request, ::villas::node::Message* response) { return this->data_echo(context, request, response); }));}
    void SetMessageAllocatorFor_data_echo(
        ::grpc::MessageAllocator< ::villas::node::Message, ::villas::node::Message>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::villas::node::Message, ::villas::node::Message>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_data_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status data_echo(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* data_echo(
      ::grpc::CallbackServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FMU_GetDataRef : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FMU_GetDataRef() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::FMU_server::Reference, ::villas::node::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FMU_server::Reference* request, ::villas::node::Message* response) { return this->FMU_GetDataRef(context, request, response); }));}
    void SetMessageAllocatorFor_FMU_GetDataRef(
        ::grpc::MessageAllocator< ::FMU_server::Reference, ::villas::node::Message>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FMU_server::Reference, ::villas::node::Message>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FMU_GetDataRef() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_GetDataRef(
      ::grpc::CallbackServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_FMU_DoStep<WithCallbackMethod_FMU_GetData<WithCallbackMethod_FMU_SetData<WithCallbackMethod_FMU_GetV<WithCallbackMethod_data_echo<WithCallbackMethod_FMU_GetDataRef<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FMU_DoStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FMU_DoStep() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FMU_DoStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_DoStep(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FMU_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FMU_GetData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FMU_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FMU_SetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FMU_SetData() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_FMU_SetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_SetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FMU_GetV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FMU_GetV() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_FMU_GetV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetV(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_data_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_data_echo() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_data_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status data_echo(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FMU_GetDataRef : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FMU_GetDataRef() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_FMU_GetDataRef() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FMU_DoStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FMU_DoStep() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FMU_DoStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_DoStep(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_DoStep(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FMU_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FMU_GetData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FMU_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_GetData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FMU_SetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FMU_SetData() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_FMU_SetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_SetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_SetData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FMU_GetV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FMU_GetV() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_FMU_GetV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetV(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_GetV(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_data_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_data_echo() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_data_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status data_echo(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdata_echo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FMU_GetDataRef : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FMU_GetDataRef() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_FMU_GetDataRef() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFMU_GetDataRef(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FMU_DoStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FMU_DoStep() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FMU_DoStep(context, request, response); }));
    }
    ~WithRawCallbackMethod_FMU_DoStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_DoStep(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_DoStep(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FMU_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FMU_GetData() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FMU_GetData(context, request, response); }));
    }
    ~WithRawCallbackMethod_FMU_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_GetData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FMU_SetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FMU_SetData() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FMU_SetData(context, request, response); }));
    }
    ~WithRawCallbackMethod_FMU_SetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_SetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_SetData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FMU_GetV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FMU_GetV() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FMU_GetV(context, request, response); }));
    }
    ~WithRawCallbackMethod_FMU_GetV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetV(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_GetV(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_data_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_data_echo() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->data_echo(context, request, response); }));
    }
    ~WithRawCallbackMethod_data_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status data_echo(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* data_echo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FMU_GetDataRef : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FMU_GetDataRef() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FMU_GetDataRef(context, request, response); }));
    }
    ~WithRawCallbackMethod_FMU_GetDataRef() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FMU_GetDataRef(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FMU_DoStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FMU_DoStep() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::villas::node::Message, ::villas::node::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::villas::node::Message, ::villas::node::Message>* streamer) {
                       return this->StreamedFMU_DoStep(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FMU_DoStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FMU_DoStep(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFMU_DoStep(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::villas::node::Message,::villas::node::Message>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FMU_GetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FMU_GetData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::villas::node::Message, ::villas::node::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::villas::node::Message, ::villas::node::Message>* streamer) {
                       return this->StreamedFMU_GetData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FMU_GetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FMU_GetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFMU_GetData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::villas::node::Message,::villas::node::Message>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FMU_SetData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FMU_SetData() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::villas::node::Message, ::villas::node::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::villas::node::Message, ::villas::node::Message>* streamer) {
                       return this->StreamedFMU_SetData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FMU_SetData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FMU_SetData(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFMU_SetData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::villas::node::Message,::villas::node::Message>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FMU_GetV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FMU_GetV() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::villas::node::Message, ::villas::node::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::villas::node::Message, ::villas::node::Message>* streamer) {
                       return this->StreamedFMU_GetV(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FMU_GetV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FMU_GetV(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFMU_GetV(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::villas::node::Message,::villas::node::Message>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_data_echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_data_echo() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::villas::node::Message, ::villas::node::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::villas::node::Message, ::villas::node::Message>* streamer) {
                       return this->Streameddata_echo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_data_echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status data_echo(::grpc::ServerContext* /*context*/, const ::villas::node::Message* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streameddata_echo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::villas::node::Message,::villas::node::Message>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FMU_GetDataRef : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FMU_GetDataRef() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FMU_server::Reference, ::villas::node::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FMU_server::Reference, ::villas::node::Message>* streamer) {
                       return this->StreamedFMU_GetDataRef(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FMU_GetDataRef() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FMU_GetDataRef(::grpc::ServerContext* /*context*/, const ::FMU_server::Reference* /*request*/, ::villas::node::Message* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFMU_GetDataRef(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FMU_server::Reference,::villas::node::Message>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FMU_DoStep<WithStreamedUnaryMethod_FMU_GetData<WithStreamedUnaryMethod_FMU_SetData<WithStreamedUnaryMethod_FMU_GetV<WithStreamedUnaryMethod_data_echo<WithStreamedUnaryMethod_FMU_GetDataRef<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FMU_DoStep<WithStreamedUnaryMethod_FMU_GetData<WithStreamedUnaryMethod_FMU_SetData<WithStreamedUnaryMethod_FMU_GetV<WithStreamedUnaryMethod_data_echo<WithStreamedUnaryMethod_FMU_GetDataRef<Service > > > > > > StreamedService;
};

}  // namespace FMU_server


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_FMU_2eproto__INCLUDED
